---
title: "HW 6.1"
format: pdf
editor: visual
---

Setup:

```{r}
if (require('HSAUR') == FALSE){
  install.packages('HSAUR')
}
if (require('Sleuth3') == FALSE){
  install.packages('Sleuth3')
}
```

### Question 1

a). 
```{r}
sales <- HSAUR::Forbes2000$sales
sum_res <- sum(sales)
for_sum <- 0
for (s in sales){
  for_sum <- for_sum + s
}

cat("Sum using sum function: ", sum_res)
cat("\nSum using for loop: ", for_sum)
```

b). Yes by using the ifelse() function inlined within the table, reshaping the data given to table().
```{r}
table(ifelse(sales > 100, yes="Greater than 100", no="Less than or equal to 100"))
```
### Question 2

a).
```{r}
A <- matrix(data=c(-5, -3, 4, 2, 1, 6), nrow=2, ncol=3, byrow=FALSE)
B <- matrix(data=c(7, 2, -9, 6, 10, 1), nrow=2, ncol=3, byrow=FALSE)
cat("The A Matrix: \n")
A
cat("The B Matrix: \n")
B
cat("----------------\n")
cat("The matrix sum is: \n")
matrix(data=A+B, nrow=2, ncol=3)
cat("\nThe matrix subtraction is: \n")
matrix(data=A-B, nrow=2, ncol=3)
```

b). 
```{r}
cat("Here is the matrix A multiplyed by c=4: \n")
4*A
```

c). # TODO: MATRIX MIGHT BE UNABLE TO MULTIPLY
```{r}
A2 <- matrix(data=c(5, 4, 1, -3, 2, 6), nrow = 2, ncol = 3, byrow = TRUE)
B2 <- matrix(data=c(7, -3, 2), nrow = 1, ncol = 3, byrow = TRUE)
A2 %*% B2
```

d).
```{r}
D <- matrix(data=c(2, -4, 5, 6, -7, 0, 3, 9, 7), nrow = 3, ncol = 3, byrow=TRUE)
D
cat("The determinant of D is: ", det(D))
```


e).
```{r}
D_inverse <- solve(D)
cat("Inverse of matrix: \n")
D_inverse

cat("Multiplication with original to produce identity matrix: \n")
round(D_inverse %*% D)
```


### Question 3

a). The formula would be $f(y;100,4) = \prod^{500}_{j=1}f(y_j;100,4) = \frac{1}{\sqrt{8\pi}}\exp(-\frac{1}{8} \sum^{500}_{j=1} (y_j-100)^2)$

```{r}
beta_matrix <- matrix(data=c(4, 2, -2, 2, 2, 1, -2, 1, 6), nrow = 3, ncol = 3, byrow = TRUE)
sol <- matrix(data=c(4, 7, 9), nrow = 3, ncol = 1, byrow = TRUE)
cat("The Beta Matrix: \n")
beta_matrix
cat("The solution vector: \n")
sol
cat("The determinant: \n")
det(beta_matrix)
cat("-------------------------\n")
cat("The solution for each respective beta starting at beta_1: \n")
solve(beta_matrix, sol)
```

### Question 4

a).
```{r}
set.seed(123457)
amat <- matrix(data = 0, nrow = 20, ncol = 4)
amat
```
b).
```{r}
set.seed(123457)
m1 <- matrix(data = 1, nrow = 2, ncol = 3)
m2 <- matrix(data = 2, nrow = 3, ncol = 3)

m3 <- matrix(data = c(m1, m2), nrow = 5, ncol = 3, byrow = TRUE)
m3
```

c).
```{r}
set.seed(123457)
m1 <- matrix(data = 1, nrow = 2, ncol = 3)
m2 <- matrix(data = 2, nrow = 2, ncol = 4)

m3 <- matrix(data = c(m1, m2), nrow = 2, ncol = 7, byrow = FALSE)
m3
```

d).
```{r}
set.seed(123457)
n = 20
one_col <- rep(1, times=n)
norm_col <- rnorm(n, mean=3, sd=sqrt(1.5))
bern_col <- rbinom(n, size=1, 0.6)

bmat <- matrix(data = c(one_col, norm_col, bern_col), nrow = n, ncol = 3, byrow = FALSE)
bmat
smat <- matrix(data = bmat[sample(n, 8), ], nrow = 8, ncol = 3)
smat

```

### Question 5

```{r}
# Fisher's z-transformation of correlation coefficient between two vars
# Use calculation on brain and body from sleuth3.case0902
# 

fishers <- function(r){
  in_log <- (1+r) / (1- r)
  return (0.5*log(in_log))
}

sample_core <- function(x, y){
  corelation <- cor(x, y)
  sd_multi <- sd(x) * sd(y)
  return(corelation / sd_multi)
}

# The mean for the normal
q5_brain <- Sleuth3::case0902$Brain
q5_body <- Sleuth3::case0902$Body

sample_cor_cof <- cor(q5_brain, q5_body)
sample_cor_cof
fish <- fishers(sample_cor_cof)
fish
Sleuth3::case0902


```




























